import 'dart:convert';

class StudioTemplate {
  const StudioTemplate({
    required this.id,
    required this.title,
    required this.category,
    required this.width,
    required this.height,
    required this.background,
    required this.ink,
    required this.accent,
    required this.headline,
    required this.subtitle,
    this.headlineFont = 'StudioSans',
    this.video = false,
  });
  final String id, title, category, headline, subtitle;
  final int width, height, background, ink, accent;
  final bool video;
  final String headlineFont;

  Map<String, dynamic> get photoRecipe => {
    'version': 1,
    'title': title,
    'width': width,
    'height': height,
    'backgroundColor': background,
    'layers': [
      {
        'id': 'accent',
        'kind': 'circle',
        'x': .62,
        'y': .52,
        'width': .62,
        'height': .55,
        'color': accent,
        'opacity': 1,
      },
      {
        'id': 'bar',
        'kind': 'rect',
        'x': .08,
        'y': .12,
        'width': .18,
        'height': .012,
        'color': accent,
      },
      {
        'id': 'eyebrow',
        'kind': 'text',
        'x': .08,
        'y': .06,
        'width': .84,
        'height': .07,
        'text': category.toUpperCase(),
        'color': ink,
        'fontSize': .025,
        'bold': false,
        'fontFamily': 'StudioMono',
      },
      {
        'id': 'headline',
        'kind': 'text',
        'x': .08,
        'y': .22,
        'width': .84,
        'height': .42,
        'text': headline,
        'color': ink,
        'fontSize': width > height ? 0.10 : 0.13,
        'fontFamily': headlineFont,
        'bold': true,
      },
      {
        'id': 'subtitle',
        'kind': 'text',
        'x': .08,
        'y': .78,
        'width': .82,
        'height': .15,
        'text': subtitle,
        'color': ink,
        'fontSize': .032,
        'fontFamily': 'StudioSans',
        'bold': false,
      },
    ],
  };
  Map<String, dynamic> createRecipe() {
    if (!video) {
      return jsonDecode(jsonEncode(photoRecipe)) as Map<String, dynamic>;
    }
    return {
      'schemaVersion': 1,
      'type': 'video',
      'title': title,
      'canvas': 'portrait',
      'clips': <dynamic>[],
      'texts': [
        {
          'id': 'title',
          'text': headline.replaceAll('\n', ' '),
          'x': .5,
          'y': .25,
          'size': .095,
          'color': ink,
          'font': headlineFont,
          'background': true,
          'start': 0,
          'end': 86400,
        },
        {
          'id': 'caption',
          'text': subtitle,
          'x': .5,
          'y': .82,
          'size': .04,
          'color': accent,
          'font': 'StudioSans',
          'background': true,
          'start': 0,
          'end': 86400,
        },
      ],
    };
  }
}

const templateCatalog = <StudioTemplate>[
  StudioTemplate(
    id: 'daily-post',
    title: 'Everyday studio',
    category: 'Instagram posts',
    width: 1080,
    height: 1080,
    background: 0xffb4a0ff,
    ink: 0xff20192c,
    accent: 0xffd4ef89,
    headline: 'MAKE IT\nYOURS.',
    subtitle: 'A fresh perspective. Your next chapter.',
  ),
  StudioTemplate(
    id: 'weekend-story',
    title: 'Weekend journal',
    category: 'Stories',
    width: 1080,
    height: 1920,
    background: 0xffadd5de,
    ink: 0xff123c40,
    accent: 0xfffca98d,
    headline: 'good\nthings\nahead.',
    subtitle: 'A little pause. A new adventure.',
  ),
  StudioTemplate(
    id: 'creator-thumb',
    title: 'The next big idea',
    category: 'YouTube thumbnails',
    width: 1280,
    height: 720,
    background: 0xff202431,
    ink: 0xfff5f3fa,
    accent: 0xffb4a0ff,
    headline: 'START\nSOMETHING.',
    subtitle: 'YOUR CHANNEL  /  NEW EPISODE',
  ),
  StudioTemplate(
    id: 'festival-lights',
    title: 'A season of light',
    category: 'Festival posters',
    width: 1080,
    height: 1350,
    background: 0xff2e153e,
    ink: 0xffffe9bb,
    accent: 0xffb97741,
    headline: 'LET YOUR\nLIGHT\nSHINE.',
    subtitle: 'Celebrate together. Make a little magic.',
  ),
  StudioTemplate(
    id: 'reel-journal',
    title: 'My little story',
    category: 'Reels',
    width: 1080,
    height: 1920,
    background: 0xff273d37,
    ink: 0xfff9ead4,
    accent: 0xffd4ef89,
    headline: 'moments\nlike these.',
    subtitle: 'A day worth remembering.',
    video: true,
  ),
  StudioTemplate(
    id: 'product-essential',
    title: 'Daily essentials',
    category: 'Product ads',
    width: 1080,
    height: 1080,
    background: 0xffe4ebc5,
    ink: 0xff263b2b,
    accent: 0xff9aad72,
    headline: 'LESS,\nBUT\nBETTER.',
    subtitle: 'YOUR BRAND  /  Discover the collection',
    headlineFont: 'StudioDisplay',
  ),
  StudioTemplate(
    id: 'business-open',
    title: 'Open for good things',
    category: 'Business posters',
    width: 1080,
    height: 1350,
    background: 0xff172b3c,
    ink: 0xffedf2f4,
    accent: 0xffb4a0ff,
    headline: 'YOUR\nNEXT\nCHAPTER.',
    subtitle: 'Grand opening  •  Your business name',
    headlineFont: 'StudioDisplay',
  ),
  StudioTemplate(
    id: 'food-post',
    title: 'A taste of the weekend',
    category: 'Instagram posts',
    width: 1080,
    height: 1080,
    background: 0xfff9c9a2,
    ink: 0xff4f211a,
    accent: 0xffed937d,
    headline: 'made\nwith\nlove.',
    subtitle: 'FRESH DAILY  /  Your menu here',
    headlineFont: 'StudioDisplay',
  ),
  StudioTemplate(
    id: 'sale-story',
    title: 'The good edit',
    category: 'Stories',
    width: 1080,
    height: 1920,
    background: 0xff343d2c,
    ink: 0xfff3efd6,
    accent: 0xffd4ef89,
    headline: 'THE\nGOOD\nEDIT.',
    subtitle: 'New arrivals. Handpicked for you.',
    headlineFont: 'StudioDisplay',
  ),
  StudioTemplate(
    id: 'reel-launch',
    title: 'Make an entrance',
    category: 'Reels',
    width: 1080,
    height: 1920,
    background: 0xff362b5e,
    ink: 0xfff9f1e1,
    accent: 0xffb4a0ff,
    headline: 'MEET\nWHAT’S\nNEXT.',
    subtitle: 'Your launch. Your moment.',
    headlineFont: 'StudioDisplay',
    video: true,
  ),
  StudioTemplate(
    id: 'tutorial-thumb',
    title: 'Create with confidence',
    category: 'YouTube thumbnails',
    width: 1280,
    height: 720,
    background: 0xffd6ec8f,
    ink: 0xff192715,
    accent: 0xff9bbe62,
    headline: 'YOU CAN\nMAKE THIS.',
    subtitle: 'THE BEGINNER’S GUIDE',
    headlineFont: 'StudioDisplay',
  ),
  StudioTemplate(
    id: 'festival-colors',
    title: 'Color the everyday',
    category: 'Festival posters',
    width: 1080,
    height: 1350,
    background: 0xffffe2bf,
    ink: 0xff542349,
    accent: 0xffe99cac,
    headline: 'MORE\nCOLOR.\nMORE JOY.',
    subtitle: 'Wishing you a beautiful celebration.',
    headlineFont: 'StudioDisplay',
  ),
  StudioTemplate(
    id: 'business-workshop',
    title: 'Ideas worth sharing',
    category: 'Business posters',
    width: 1080,
    height: 1350,
    background: 0xffdad8f0,
    ink: 0xff262139,
    accent: 0xffb4a0ff,
    headline: 'LET’S\nBUILD\nTOGETHER.',
    subtitle: 'WORKSHOP  /  Date • Time • Location',
    headlineFont: 'StudioDisplay',
  ),
  StudioTemplate(
    id: 'product-drop',
    title: 'Your new favorite',
    category: 'Product ads',
    width: 1080,
    height: 1350,
    background: 0xfff4d7cd,
    ink: 0xff492b2d,
    accent: 0xffce9b9d,
    headline: 'HELLO,\nNEW\nFAVORITE.',
    subtitle: 'THE LATEST DROP  /  Your store here',
    headlineFont: 'StudioDisplay',
  ),
];
