"""Write a readable snapshot of maintained source for all ten phases.

No build outputs, machine-specific SDK settings, credentials or binary assets
are copied. The source files remain authoritative; rerun after code changes.
"""
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
files = [root / name for name in ("pubspec.yaml", "pubspec.lock", "analysis_options.yaml", ".gitignore", ".gitattributes", ".metadata")]
for folder in ("lib", "test", "integration_test", "test_driver", "scripts"):
    files.extend(p for p in (root / folder).rglob("*") if p.is_file() and p.suffix in {".dart", ".ps1", ".py"})
files.extend(p for p in (root / "android").rglob("*") if p.is_file()
             and p.suffix in {".kt", ".kts", ".xml", ".properties", ".pro"}
             and not any(part in {".gradle", ".kotlin", "build"} for part in p.relative_to(root / "android").parts)
             and p.name not in {"local.properties", "key.properties"})
files.extend(root / "android" / n for n in ("gradlew", "gradlew.bat", ".gitignore", "key.properties.example"))
files.append(root / "docs" / "ASSET_MANIFEST.json")
for folder in ("assets/fonts", "assets/licenses", "android/app/src/main/assets/models"):
    files.extend((root / folder).glob("*.txt"))
files = sorted(set(p for p in files if p.exists()), key=lambda p: p.relative_to(root).as_posix())
output = [
    "# Complete source — Phases 1–10\n",
    "Generated by `python scripts/export_source.py`. Individual files are the editable source of truth. "
    "This snapshot contains application, native bridge, tests, build configuration, developer scripts, "
    "asset manifest and bundled text notices. Binary fonts, ONNX model, Android wrapper JAR and PNG icons "
    "remain in the project. No machine-specific local.properties, credentials or build/cache output is included. "
    "Phase reports and actual validation results live beside this file. The historical Phase 1 snapshot "
    "is retained separately as PHASE_01_SOURCE.md.\n",
    f"Files included: **{len(files)}**.\n",
]
for path in files:
    name = path.relative_to(root).as_posix()
    lang = {".dart": "dart", ".yaml": "yaml", ".kts": "kotlin", ".kt": "kotlin", ".xml": "xml", ".ps1": "powershell", ".py": "python", ".json": "json"}.get(path.suffix, "text")
    content = path.read_text(encoding="utf-8-sig").rstrip()
    fence = "`" * max(3, 1 + max((len(run) for run in re.findall(r"`+", content)), default=0))
    output.append(f"## {name}\n\n{fence}{lang}\n{content}\n{fence}\n")
(root / "docs" / "COMPLETE_SOURCE.md").write_text("\n".join(output), encoding="utf-8")
print(f"Snapshot written: {len(files)} complete source/configuration files")
